proxies/live/apiproxy/policies/ServiceCallout.CallHealthcheckEndpoint.xml
proxies/sandbox/apiproxy/policies/ServiceCallout.CallHealthcheckEndpoint.xml
sandbox/handlers.js

Updates redirection and response from _status endpoint

AEA-3248 Updates Status Responses

---

azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml
proxies/live/apiproxy/policies/AssignMessage.OverridePatientAccessHeader.xml
proxies/live/apiproxy/targets/target.xml

allow nhs number override in some environments

---

azure/azure-release-pipeline.yml

AEA-3456 put manual approval steps in for release to ptl environments

---

azure/azure-release-pipeline.yml
manifest_template.yml

increase ref rate limits

---

azure/azure-release-pipeline.yml

add manaual approval steps

---

azure/azure-release-pipeline.yml

put correct environment for gated release

---

package-lock.json
package.json

Removed unnecessary NPM dependencies and npm audit fix

---

azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml

AEA-3456 fix approvals for PTL releases

---

azure/azure-release-pipeline.yml
manifest_template.yml

Add any summary information of what is in the change. **Remove this line if you have nothing to add.**

AEA-3496 Added prod environment

---

azure/azure-release-pipeline.yml

Add any summary information of what is in the change. **Remove this line if you have nothing to add.**

AEA-3496 Fixed production approvals

---

azure/azure-release-pipeline.yml

Add any summary information of what is in the change. **Remove this line if you have nothing to add.**

AEA-3496 Fixed approval group for lower envs.

---

azure/azure-release-pipeline.yml
manifest_template.yml

Disable status monitor in prod while we configure target server correctly

disable monitoring in prod

---

proxies/live/apiproxy/targets/target.xml

Fixes unauthorized response message so it is valid FHIR

AEA-3553 fix unauthorized response

---

azure/azure-release-pipeline.yml

Enable status monitoring in prod

enable prod status monitoring

---

tests/test_endpoints.py

Adds x-correlation-id header to tests

add x-correlation-id to tests

---

.github/workflows/dependabot_auto_approve_and_merge.yml

squash dependabot prs

---

proxies/live/apiproxy/policies/FlowCallout.LogToSplunk.xml
proxies/live/apiproxy/policies/FlowCallout.LogToSplunkRequestContentBody.xml
proxies/live/apiproxy/policies/FlowCallout.SetSplunkPayload.xml
proxies/live/apiproxy/proxies/default.xml

Use shared flow LogToSplunkRequestContentBody to log to splunk so that client sent_start and sent_end are logged

AEA-3652 Log client sent_start and sent_end to splunk to show response times

---

.github/workflows/dependabot_auto_approve_and_merge.yml

Use PAT for dependabot automerge

use PAT for dependabot automerge

---

README.md

Fix build status badge on readme

AEA-3702 fix build status badge

---

specification/examples/GetMyPrescriptions/Bundle/success-multiple-exclusion.json
specification/examples/GetMyPrescriptions/Bundle/success-single-exclusion.json
specification/prescriptions-for-patients.yaml
specification/schemas/resources/OperationOutcome.yaml

Updates the schema and adds examples of OperationOutcome/s being included in the PfP response if prescriptions cannot be processed.

[AEA-3561] Publish Schema for PfP response to enable prescription to be excluded due to processing error

---

specification/examples/GetMyPrescriptions/Bundle/success-distance-selling.json
specification/prescriptions-for-patients.yaml
specification/schemas/fragments/telecom.yaml
specification/schemas/resources/Organisation.yaml

Jira Reference: [AEA-3687](https://nhsd-jira.digital.nhs.uk/browse/AEA-3687)
This repository contains the codebase and documentation for updating the PfP API specification in response to the user story described in ticket [AEA-3450](https://nhsd-jira.digital.nhs.uk/browse/AEA-3450). The focus is on incorporating the distance selling pharmacy website URL within the telecom array of the API response, facilitating seamless integration for NHS App developers.
A list of what the solution must do:
1. The solution must publish an updated PfP API specification to reflect the decision to pass back the website URL for distance selling pharmacies in the telecom array within the performer organisation resource.
2. The …

AEA-3687 Update PfP API Specification to reflect decision to return URL in telecom array

---

.github/workflows/dependabot_auto_approve_and_merge.yml

- use app for autoapprove dependabot pull requests

use app for dependabot auto approve

---

.devcontainer/Dockerfile
.github/workflows/continuous-integration.yml
.github/workflows/dependabot_auto_approve_and_merge.yml
.github/workflows/pr-link.yml
.pre-commit-config.yaml
.tool-versions
Makefile

- :robot: Operational or Infrastructure Change

AEA-3622 Fix GitHub actionlint errors and enable

---

specification/examples/GetMyPrescriptions/Bundle/success/success-distance-selling.json
specification/examples/GetMyPrescriptions/Bundle/success/success-multiple-exclusion.json
specification/examples/GetMyPrescriptions/Bundle/success/success-multiple.json
specification/examples/GetMyPrescriptions/Bundle/success/success-single-exclusion.json
specification/examples/GetMyPrescriptions/Bundle/success/success.json
specification/schemas/fragments/medicationRequest/status.yaml
specification/schemas/fragments/medicationRequest/statusDate.yaml
specification/schemas/resources/MedicationRequest.yaml

Updates OAS spec and examples to include line item status, terminal status, status timestamp, and additional instructions.

AEA-3807 Update PfP API Specification to include prescription tracking data

---

specification/examples/GetMyPrescriptions/Bundle/success/success-distance-selling.json
specification/examples/GetMyPrescriptions/Bundle/success/success-multiple-cancelled.json
specification/examples/GetMyPrescriptions/Bundle/success/success-multiple-exclusion.json
specification/examples/GetMyPrescriptions/Bundle/success/success-multiple.json
specification/examples/GetMyPrescriptions/Bundle/success/success-single-exclusion.json
specification/examples/GetMyPrescriptions/Bundle/success/success.json
specification/prescriptions-for-patients.yaml
specification/schemas/fragments/medicationRequest/status.yaml

Updating spec to include new tracking states, also updating descriptions and example messages to reflect the new tracking states.

AEA-3940-Update-spec-include-new-tracking-states

---

Makefile

fix case on rc page title

---

specification/examples/GetMyPrescriptions/Bundle/success/success-ready-dispatch.json
specification/prescriptions-for-patients.yaml
specification/schemas/fragments/medicationRequest/status.yaml

Added new ready to dispatch and partial status to schema, examples and descriptions.

AEA-4007-Added-Ready-to-dispatch-status

---

azure/azure-release-pipeline.yml

Fix: [AEA-4121] - use new stack for ref

---

proxies/sandbox/apiproxy/targets/sandbox.xml

- use new stack for sandbox environments

Fix: [AEA-4132] - use new stack for sandbox environments

---

azure/azure-release-pipeline.yml
proxies/live/apiproxy/policies/ServiceCallout.CallHealthcheckEndpoint.xml
proxies/sandbox/apiproxy/policies/ServiceCallout.CallHealthcheckEndpoint.xml

- set status endpoint target server to point to correct stack
- correct using sandbox proxy for sandbox environments

Fix: [AEA-0000] - set status endpoint target server to point to correct stack

---

azure/azure-release-pipeline.yml

Fix: [AEA-0000] - fix sandbox deployment

---

azure/azure-release-pipeline.yml

- make qa environment connect to new stack

Fix: [AEA-4117] - qa connects to new stack

---

azure/azure-release-pipeline.yml

Fix: [AEA-4116] - int to new stack

---

azure/azure-release-pipeline.yml

Fix: [AEA-0000] - point int to old pfp stack

---

azure/azure-release-pipeline.yml

Fix: [AEA-0000] - point int to new stack

---

SECURITY.md

Docs: [AEA-4306] - update security.md

---

specification/prescriptions-for-patients.yaml

Update OAS to reflect silver service level

Docs: [AEA-4282] - Update OAS to reflect silver service level

---

proxies/live/apiproxy/proxies/default.xml
proxies/sandbox/apiproxy/proxies/default.xml
specification/prescriptions-for-patients.yaml

🎫 [AEA-4312](https://nhsd-jira.digital.nhs.uk/browse/AEA-4312) Failed to fetch (CORS or Network Issue)
- :warning: Potential issues that might be caused by this change
Observed Behaviour
- An error is returned 'Failed to fetch (CORS or Network Issue)'
- Authentication shows None Applied

Fix: [AEA-4312] - Failed to fetch (CORS or Network Issue)

---

azure/templates/run_tests.yml
scripts/run_regression_tests.py

- show links to reports on test failures
- generic script that can be run from github or azure
- run from tag

Chore: [AEA-0000] - update run regression

---

.github/workflows/combine-dependabot-prs.yml
.github/workflows/continuous-integration.yml
.github/workflows/create_int_release_notes.yml
.github/workflows/create_prod_release_notes.yml
.github/workflows/create_rc_int_release_notes.yml
.github/workflows/dependabot_auto_approve_and_merge.yml
.github/workflows/mark_jira_released.yml
.github/workflows/pr-link.yml
.github/workflows/pr_title_check.yml

- pin ubuntu in github actions

Fix: [AEA-0000] - pin ubuntu in github actions

---

scripts/run_regression_tests.py

- use the latest regression tests

Fix: [AEA-0000] - use latest regression test

---

poetry.lock
pyproject.toml

Addresses the following: 
https://github.com/NHSDigital/prescriptions-for-patients/security/dependabot/83

Chore: [AEA-0000] - Update python dependency to address cryptography issue

---

.devcontainer/Dockerfile
.github/workflows/continuous-integration.yml
.github/workflows/create_int_release_notes.yml
.github/workflows/create_prod_release_notes.yml
.github/workflows/create_rc_int_release_notes.yml
.github/workflows/mark_jira_released.yml
pyproject.toml

Fix: [AEA-0000] - use asdf 15
